-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`BREND`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BREND` (
  `IDBREND` INT NOT NULL AUTO_INCREMENT,
  `IME_BRENDA` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IDBREND`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KATEGORIJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KATEGORIJA` (
  `IDKATEGORIJE` INT NOT NULL AUTO_INCREMENT,
  `NAZIV_KATEGORIJE` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IDKATEGORIJE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OBLIK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OBLIK` (
  `IDOBLIK` INT NOT NULL AUTO_INCREMENT,
  `NAZIV_OBLIKA` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IDOBLIK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STAKLO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STAKLO` (
  `IDSTAKLO` INT NOT NULL AUTO_INCREMENT,
  `VRSTA_STAKLA` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IDSTAKLO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NAOCARE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NAOCARE` (
  `IDNAOCARE` INT NOT NULL AUTO_INCREMENT,
  `NAZIV` VARCHAR(45) NULL DEFAULT NULL,
  `CENA` DOUBLE NULL DEFAULT NULL,
  `BREND_IDBREND` INT NOT NULL,
  `KATEGORIJA_IDKATEGORIJE` INT NOT NULL,
  `OBLIK_IDOBLIK` INT NOT NULL,
  `STAKLO_IDSTAKLO` INT NOT NULL,
  `SLIKA` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`IDNAOCARE`),
  INDEX `fk_NAOCARE_BREND_idx` (`BREND_IDBREND` ASC) VISIBLE,
  INDEX `fk_NAOCARE_KATEGORIJA1_idx` (`KATEGORIJA_IDKATEGORIJE` ASC) VISIBLE,
  INDEX `fk_NAOCARE_OBLIK1_idx` (`OBLIK_IDOBLIK` ASC) VISIBLE,
  INDEX `fk_NAOCARE_STAKLO1_idx` (`STAKLO_IDSTAKLO` ASC) VISIBLE,
  CONSTRAINT `fk_NAOCARE_BREND`
    FOREIGN KEY (`BREND_IDBREND`)
    REFERENCES `mydb`.`BREND` (`IDBREND`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NAOCARE_KATEGORIJA1`
    FOREIGN KEY (`KATEGORIJA_IDKATEGORIJE`)
    REFERENCES `mydb`.`KATEGORIJA` (`IDKATEGORIJE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NAOCARE_OBLIK1`
    FOREIGN KEY (`OBLIK_IDOBLIK`)
    REFERENCES `mydb`.`OBLIK` (`IDOBLIK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NAOCARE_STAKLO1`
    FOREIGN KEY (`STAKLO_IDSTAKLO`)
    REFERENCES `mydb`.`STAKLO` (`IDSTAKLO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PORUDZBINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PORUDZBINA` (
  `IDPORUDZBINE` INT NOT NULL AUTO_INCREMENT,
  `NARUCILAC` VARCHAR(45) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(45) NULL DEFAULT NULL,
  `ADRESA` VARCHAR(45) NULL DEFAULT NULL,
  `DATUM_ISPORUKE` DATE NULL DEFAULT NULL,
  `NACIN_PLACANJA` VARCHAR(20) NULL DEFAULT NULL,
  `UKUPNA_CENA` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`IDPORUDZBINE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OCENA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OCENA` (
  `IDOCENA` INT NOT NULL AUTO_INCREMENT,
  `OCENA` DOUBLE NULL DEFAULT NULL,
  `KOMENTAR` VARCHAR(100) NULL DEFAULT NULL,
  `NAOCARE_IDNAOCARE` INT NOT NULL,
  PRIMARY KEY (`IDOCENA`),
  INDEX `fk_OCENA_NAOCARE1_idx` (`NAOCARE_IDNAOCARE` ASC) VISIBLE,
  CONSTRAINT `fk_OCENA_NAOCARE1`
    FOREIGN KEY (`NAOCARE_IDNAOCARE`)
    REFERENCES `mydb`.`NAOCARE` (`IDNAOCARE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PORUDZBINA_has_NAOCARE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PORUDZBINA_has_NAOCARE` (
  `PORUDZBINA_IDPORUDZBINE` INT NOT NULL,
  `NAOCARE_IDNAOCARE` INT NOT NULL,
  PRIMARY KEY (`PORUDZBINA_IDPORUDZBINE`, `NAOCARE_IDNAOCARE`),
  INDEX `fk_PORUDZBINA_has_NAOCARE_NAOCARE1_idx` (`NAOCARE_IDNAOCARE` ASC) VISIBLE,
  INDEX `fk_PORUDZBINA_has_NAOCARE_PORUDZBINA1_idx` (`PORUDZBINA_IDPORUDZBINE` ASC) VISIBLE,
  CONSTRAINT `fk_PORUDZBINA_has_NAOCARE_PORUDZBINA1`
    FOREIGN KEY (`PORUDZBINA_IDPORUDZBINE`)
    REFERENCES `mydb`.`PORUDZBINA` (`IDPORUDZBINE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PORUDZBINA_has_NAOCARE_NAOCARE1`
    FOREIGN KEY (`NAOCARE_IDNAOCARE`)
    REFERENCES `mydb`.`NAOCARE` (`IDNAOCARE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DODATAK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DODATAK` (
  `IDDODATAK` INT NOT NULL AUTO_INCREMENT,
  `NAZIV_DODATKA` VARCHAR(100) NULL DEFAULT NULL,
  `CENA` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`IDDODATAK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DODATAK_has_PORUDZBINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DODATAK_has_PORUDZBINA` (
  `DODATAK_IDDODATAK` INT NOT NULL,
  `PORUDZBINA_IDPORUDZBINE` INT NOT NULL,
  PRIMARY KEY (`DODATAK_IDDODATAK`, `PORUDZBINA_IDPORUDZBINE`),
  INDEX `fk_DODATAK_has_PORUDZBINA_PORUDZBINA1_idx` (`PORUDZBINA_IDPORUDZBINE` ASC) VISIBLE,
  INDEX `fk_DODATAK_has_PORUDZBINA_DODATAK1_idx` (`DODATAK_IDDODATAK` ASC) VISIBLE,
  CONSTRAINT `fk_DODATAK_has_PORUDZBINA_DODATAK1`
    FOREIGN KEY (`DODATAK_IDDODATAK`)
    REFERENCES `mydb`.`DODATAK` (`IDDODATAK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DODATAK_has_PORUDZBINA_PORUDZBINA1`
    FOREIGN KEY (`PORUDZBINA_IDPORUDZBINE`)
    REFERENCES `mydb`.`PORUDZBINA` (`IDPORUDZBINE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
