-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`NAOCARESHOP_ULOGA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NAOCARESHOP_ULOGA` (
  `IDULOGA` INT NOT NULL AUTO_INCREMENT,
  `NAZIV` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IDULOGA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NAOCARESHOP_KORISNIK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NAOCARESHOP_KORISNIK` (
  `IDKORISNIK` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(45) NULL DEFAULT NULL,
  `PASSWORD` VARCHAR(255) NULL DEFAULT NULL,
  `IME` VARCHAR(45) NULL DEFAULT NULL,
  `PREZIME` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IDKORISNIK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NAOCARESHOP_ULOGA_has_NAOCARESHOP_KORISNIK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NAOCARESHOP_ULOGA_has_NAOCARESHOP_KORISNIK` (
  `NAOCARESHOP_ULOGA_IDULOGA` INT NOT NULL,
  `NAOCARESHOP_KORISNIK_IDKORISNIK` INT NOT NULL,
  PRIMARY KEY (`NAOCARESHOP_ULOGA_IDULOGA`, `NAOCARESHOP_KORISNIK_IDKORISNIK`),
  INDEX `fk_NAOCARESHOP_ULOGA_has_NAOCARESHOP_KORISNIK_NAOCARESHOP_K_idx` (`NAOCARESHOP_KORISNIK_IDKORISNIK` ASC) VISIBLE,
  INDEX `fk_NAOCARESHOP_ULOGA_has_NAOCARESHOP_KORISNIK_NAOCARESHOP_U_idx` (`NAOCARESHOP_ULOGA_IDULOGA` ASC) VISIBLE,
  CONSTRAINT `fk_NAOCARESHOP_ULOGA_has_NAOCARESHOP_KORISNIK_NAOCARESHOP_ULO`
    FOREIGN KEY (`NAOCARESHOP_ULOGA_IDULOGA`)
    REFERENCES `mydb`.`NAOCARESHOP_ULOGA` (`IDULOGA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NAOCARESHOP_ULOGA_has_NAOCARESHOP_KORISNIK_NAOCARESHOP_KOR1`
    FOREIGN KEY (`NAOCARESHOP_KORISNIK_IDKORISNIK`)
    REFERENCES `mydb`.`NAOCARESHOP_KORISNIK` (`IDKORISNIK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
